feat: Enable fib_e2e benchmark (#838)
* feat: enable fib_e2e benchmark, to be run only when run-benchmark label is present

* fix: debug statement

* fix: more debug statements

* fix: convert github label array to JSON

* fix: merge to gh-pages isntead of force push

* fix: spinlock gh-pages push

* feat: change label to e2e

* fix: matrix not generating properly

* fix: matrix for e2e bench

* fix: another try

* feat: specify whether a benchmark is e2e in config

* fix: new config.json location

* fix: debug statements

* fix: more debugging

* fix: e2e bench check

* chore: some cleanup

* fix: more debug

* fix: fix debug

* fix: more debug

* fix: properly set e2e_bench in benchmark

* fix: correctly split regular and e2e benchmarks in summarize

* feat: remove cleaner + docs + rollout

* fix: summarize call

* fix: download e2e files too

* fix: some debug

* chore: revert debug stuff + add table headers in summarize

* fix: e2e shouldn't run on push

diff --git a/.github/workflows/benchmark-call.yml b/.github/workflows/benchmark-call.yml
--- a/.github/workflows/benchmark-call.yml
+++ b/.github/workflows/benchmark-call.yml
@@ -13,6 +13,7 @@ on:
           - revm_transfer
           - regex
           - base64_json
+          - fib_e2e
       instance_type:
         type: string
         required: false
@@ -31,7 +32,17 @@ on:
       agg_log_blowup:
         type: number
         required: false
-        description: Aggregation level log blowup
+        description: Aggregation (leaf) level log blowup
+        default: 2
+      root_log_blowup:
+        type: number
+        required: false
+        description: Root level log blowup (only for e2e)
+        default: 2
+      internal_log_blowup:
+        type: number
+        required: false
+        description: Internal level log blowup (only for e2e)
         default: 2
   workflow_call:
     inputs:
@@ -57,7 +68,17 @@ on:
       agg_log_blowup:
         type: number
         required: false
-        description: Aggregation level log blowup
+        description: Aggregation (leaf) level log blowup
+        default: 2
+      root_log_blowup:
+        type: number
+        required: false
+        description: Root level log blowup (only for e2e)
+        default: 2
+      internal_log_blowup:
+        type: number
+        required: false
+        description: Internal level log blowup (only for e2e)
         default: 2
 
 env:
@@ -66,6 +87,7 @@ env:
   PUBLIC_S3_PATH: s3://axiom-public-data-sandbox-us-east-1/benchmark/github/flamegraphs
   FEATURE_FLAGS: "bench-metrics,parallel"
   CMD_ARGS: ""
+  INPUT_ARGS: ""
 
 jobs:
   bench-new:
@@ -123,12 +145,22 @@ jobs:
           echo "Adding aggregation feature flag"
           echo "FEATURE_FLAGS=${FEATURE_FLAGS},aggregation" >> $GITHUB_ENV
 
-      - name: Setup halo2
+      - name: Setup e2e (halo2 and arguments)
         working-directory: lib/recursion # We only ever run halo2 for recursion
         run: |
-          if [[ "${{ github.event.pull_request.labels[*].name }}" == *"run-benchmark-e2e"* ]]; then
+          E2E_BENCH=$(jq -r --arg name "${{ inputs.benchmark_name }}" '
+            .benchmarks[] |
+            select(.name == $name) |
+            .e2e_bench
+          ' ../../ci/benchmark-config.json)
+          echo "E2E_BENCH=${E2E_BENCH}" >> $GITHUB_ENV
+
+          if [[ "${E2E_BENCH}" == "true" ]]; then
             echo "Adding static-verifier feature flag"
             echo "FEATURE_FLAGS=${FEATURE_FLAGS},static-verifier" >> $GITHUB_ENV
+            ROOT_ARG="--root_log_blowup ${{ inputs.root_log_blowup }}"
+            INTERNAL_ARG="--internal_log_blowup ${{ inputs.internal_log_blowup }}"
+            echo "INPUT_ARGS=${ROOT_ARG} ${INTERNAL_ARG} ${INPUT_ARGS}" >> $GITHUB_ENV
             bash trusted_setup_s3.sh
           fi
 
@@ -144,7 +176,7 @@ jobs:
           MEMORY_ALLOCATOR="--memory_allocator ${{ inputs.memory_allocator }}"
           APP_ARG="--app_log_blowup ${{ inputs.app_log_blowup }}"
           AGG_ARG="--agg_log_blowup ${{ inputs.agg_log_blowup }}"
-          echo "INPUT_ARGS=${INSTANCE_TYPE} ${MEMORY_ALLOCATOR} ${APP_ARG} ${AGG_ARG}" >> $GITHUB_ENV
+          echo "INPUT_ARGS=${INSTANCE_TYPE} ${MEMORY_ALLOCATOR} ${APP_ARG} ${AGG_ARG} ${INPUT_ARGS}" >> $GITHUB_ENV
 
       - name: Set working directory
         id: set-working-dir
@@ -171,7 +203,11 @@ jobs:
       ##########################################################################
       - name: Store metric json and compute diff with previous
         run: |
-          METRIC_NAME="${BIN_NAME}-${{ inputs.app_log_blowup }}-${{ inputs.agg_log_blowup }}-${{ inputs.instance_type }}-${{ inputs.memory_allocator }}"
+          METRIC_NAME="${BIN_NAME}-${{ inputs.app_log_blowup }}-${{ inputs.agg_log_blowup }}"
+          if [[ "${E2E_BENCH}" == "true" ]]; then
+            METRIC_NAME="${METRIC_NAME}-${{ inputs.root_log_blowup }}-${{ inputs.internal_log_blowup }}"
+          fi
+          METRIC_NAME="${METRIC_NAME}-${{ inputs.instance_type }}-${{ inputs.memory_allocator }}"
           echo "METRIC_NAME=${METRIC_NAME}" >> $GITHUB_ENV
 
           METRIC_PATH=".bench_metrics/${METRIC_NAME}.json"
@@ -236,32 +272,6 @@ jobs:
           echo "[Benchmark Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $RESULT_PATH
           s5cmd cp $RESULT_PATH "${{ env.S3_PATH }}/${current_sha}-${METRIC_NAME}.md"
 
-      # TODO[stephenh]: remove this collapse after old PR workflow phased out
-      - name: Collapse previous comment (if exists)
-        if: github.event_name == 'pull_request'
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const comments = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number
-            });
-            for (const comment of comments.data) {
-              if (comment.user.login == "github-actions[bot]" && comment.body.startsWith("<!--${{ inputs.benchmark_name }}-->")) {
-                console.log("collapse comment ", comment.id);
-                const resp = await github.graphql(`
-                  mutation {
-                    minimizeComment(input: {classifier: OUTDATED, subjectId: "${comment.node_id}"}) {
-                      minimizedComment {
-                        isMinimized
-                      }
-                    }
-                  }
-                `);
-              }
-            }
-
       ##########################################################################
       # Update S3 with individual results upon a push event                    #
       ##########################################################################
@@ -308,4 +318,27 @@ jobs:
           s5cmd cp "${{ env.S3_PATH }}/${{ env.current_sha }}-${METRIC_NAME}.md" ${GH_PAGES_PATH}/${METRIC_NAME}.md
           git add ${GH_PAGES_PATH}/${METRIC_NAME}.md
           git commit --allow-empty -m "Update benchmark result at ${GH_PAGES_PATH}/${METRIC_NAME}.md"
-          git push --force
+
+          MAX_RETRIES=10
+          RETRY_DELAY=5
+          ATTEMPT=0
+          SUCCESS=false
+
+          while [ $ATTEMPT -lt $MAX_RETRIES ]; do
+              echo "Attempt $((ATTEMPT + 1)) to push of $MAX_RETRIES..."
+              git fetch origin gh-pages
+              git merge origin/gh-pages --no-edit
+              if git push origin gh-pages; then
+                  SUCCESS=true
+                  break
+              else
+                  echo "Push failed. Retrying in $RETRY_DELAY seconds..."
+                  sleep $RETRY_DELAY
+                  ATTEMPT=$((ATTEMPT + 1))
+              fi
+          done
+
+          if [ "$SUCCESS" = false ]; then
+              echo "PUSH_FAILED"
+              exit 1
+          fi
